/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Datos.DATFuncionalidades;
import Entidades.PDF;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.*;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author LENOVO
 */
public class Principal extends javax.swing.JFrame {
    boolean clave = true;
    
    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setContentPane(fondo);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/IMG/help.png")).getImage());
        this.setSize(new Dimension(1200, 800));
        //this.setMinimumSize(new Dimension(200, 200));
        setLocationRelativeTo(null);
        btnFuncionalidades.setBackground(Color.CYAN);
        btnPracticas.setBackground(Color.CYAN);
        this.setResizable(false);
        
        setTitle("EasyLab - Asesoramiento ");

    }
     public void imagenDesktop(){
         
     }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFuncionalidades = new javax.swing.JButton();
        btnPracticas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1300, 800));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Herramienta WBS Schedule Pro");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dep.jpg"))); // NOI18N
        jLabel2.setText(" ");

        btnFuncionalidades.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnFuncionalidades.setText("FUNCIONALIDADES");
        btnFuncionalidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuncionalidadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionalidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionalidadesMouseExited(evt);
            }
        });

        btnPracticas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPracticas.setText("PRÁCTICAS");
        btnPracticas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnPracticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPracticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPracticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPracticasMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/programador.jpg"))); // NOI18N
        jLabel1.setText(" ");

        jLabel5.setFont(new java.awt.Font("Kozuka Mincho Pro R", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 233, 233));
        jLabel5.setText("Descripción de todas las funcionalidades");

        jLabel6.setFont(new java.awt.Font("Kozuka Mincho Pro R", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 233, 233));
        jLabel6.setText("Manuales de desarrollo");

        jLabel7.setFont(new java.awt.Font("Kozuka Mincho Pro R", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 233, 233));
        jLabel7.setText("que posee la herramienta");

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("EasyLab");

        jMenu1.setText("Opciones");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        jMenuItem.setText("Salir");
        jMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemMouseClicked(evt);
            }
        });
        jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem);

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleDescription("");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(542, 542, 542)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160)
                .addComponent(btnPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel5)
                .addGap(256, 256, 256)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFuncionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addComponent(jLabel7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemMouseClicked
  
    }//GEN-LAST:event_jMenuItemMouseClicked

    private void jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActionPerformed
        //// TODO add your handling code here:
        //WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        //Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        FeedBack fbck = new FeedBack();
        Principal pl = new Principal();
        int valor = JOptionPane.showConfirmDialog(this, "¿Desea calificar el aplicativo antes de salir?", "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (valor == JOptionPane.YES_OPTION) {
           fbck.setVisible(true);
           pl.dispose();
        }
        else{
            System.exit(0);
            
        }
        this.dispose();
    }//GEN-LAST:event_jMenuItemActionPerformed

    private void btnPracticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPracticasMouseClicked
        // TODO add your handling code here:
        Pantalla_Practicas vista = new Pantalla_Practicas();
        if (clave == false) {
            vista.setVisible(clave);

        }else{
            vista.setVisible(clave);
            dispose();
        }
    }//GEN-LAST:event_btnPracticasMouseClicked

    private void btnFuncionalidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionalidadesMouseClicked
        // TODO add your handling code here:
        try {
            PDF valor = new PDF();
            DATFuncionalidades pd = new DATFuncionalidades();
            valor = pd.Presentar_PDF();
            pd.ejecutar_archivoPDF(valor);
            //System.err.println("valor: "+valor.toString());
            Desktop.getDesktop().open(new File("Recursos\\Funcionalidades.pdf"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Problemas al Encontrar el Archivo");
        }
    }//GEN-LAST:event_btnFuncionalidadesMouseClicked

    private void btnFuncionalidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionalidadesMouseEntered
        // TODO add your handling code here:
        btnFuncionalidades.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnFuncionalidadesMouseEntered

    private void btnFuncionalidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionalidadesMouseExited
        // TODO add your handling code here:
        btnFuncionalidades.setBackground(Color.CYAN);
    }//GEN-LAST:event_btnFuncionalidadesMouseExited

    private void btnPracticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPracticasMouseEntered
        // TODO add your handling code here:
        btnPracticas.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnPracticasMouseEntered

    private void btnPracticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPracticasMouseExited
        // TODO add your handling code here:
        btnPracticas.setBackground(Color.CYAN);
    }//GEN-LAST:event_btnPracticasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFuncionalidades;
    private javax.swing.JButton btnPracticas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem;
    // End of variables declaration//GEN-END:variables
    class FondoPanel extends JPanel{
        private Image imagen;
        @Override
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("/IMG/utpl2.jpg")).getImage();
            
            g.drawImage(imagen , 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
            
        }
    }

}

